### PR TITLE
ensure cron runs in the context of UTC

### LINKED ISSUE #48: Wrong start time calculated when machine time zone is not UTC
I submitted the job with the schedule ``13 18 * * 1-5``, expecting the job to be schedule at 18:15. When deployed to a machine with the ``US/Pacific`` timezone, I see the following:

```
Dec 13 07:25:57 paasta1-uswest1adevc chronos[128714]: [2016-12-13 07:25:57,863] INFO Next iteration for job reminder standup-reminder-paasta-tuesday is at 2016-12-14T02:13:00.000Z: too far in the future; not scheduling in this schedule horizon.
```

Which is 18:13 ``US/Pacific`` time.

### PR DESCRIPTION
**Pull request by Rob-Johnson**
closes #48 - when parsing the cron, make sure that we get the next execution in terms of UTC

### CODE REVIEW

**Comment by Rob-Johnson** [comment]
I've tested this manually, but I'm struggling to write a unit test that can mock the system time zone.

File: src/test/scala/org/apache/mesos/chronos/schedule/CronParserSpec.scala [hunk 1]
```diff
@@ -22,4 +24,13 @@ class CronParserSpec extends SpecificationWithJUnit{
      result must beNone
    }
  }
+}
+
+class CronParserAltTZSpec extends SpecificationWithJUnit with AlternativeTimezoneTest {
+  "In US/Pacific Cron Parser should" in {
+   "Return the schedule in UTC" in {
+     val result = CronParser("0 18 * * *")
+     result.get.start.hourOfDay().get must_== 18
```
Comment (tub) [inline src/test/scala/org/apache/mesos/chronos/schedule/CronParserSpec.scala:33]: So this means that cron expressions are parsed in the context of 'the current timezone'. Which I guess is right (well, more correct than the other option).

**Review by tub — APPROVED** [review]

File: src/test/scala/org/apache/mesos/chronos/schedule/CronParserSpec.scala (hunk 1 above)
Comment (Rob-Johnson) [reply src/test/scala/org/apache/mesos/chronos/schedule/CronParserSpec.scala:33]: er, no, it means that they're *always* parsed in UTC (The AlternativeTimezoneTest class forces US/Pacific).
